name: Sync issue to Azure DevOps work item (testing)

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened]

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.labels.*.name, 'pager-duty')
        name: custom issues
        env:
          DISCORD_WEBHOOK: ${{ secrets.PAGERDUTY_DISCORD_WEBHOOK}}
          
        uses: devtron-labs/action-discord@master
        with:
          args: " [ **${{ github.event.issue.title}}** ](${{github.event.issue.html_url}})"
