name: Validate Issue Reference

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    # branches:    
    #   - 'main'
    #   - 'release-**'
    # paths-ignore:
    #   - 'docs/**'
    #   - '.github/'
    #   - 'CHANGELOG/'
    #   - 'charts/'
    #   - 'manifests/'
    #   - 'sample-docker-templates/'

jobs:
  validate-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check for valid issue reference
        uses: actions/checkout@v2

      - name: Validate Issue Reference
        run: |
          sudo apt-get update
          sudo apt-get install jq
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          echo "PR_BODY"
          echo $PR_BODY
          ISSUE_REGEX='(Fixes|Resolves) ((#(\d+))|(https:\/\/github.com\/[^\/]+\/[^\/]+\/issues\/(\d+)))'
          if echo "$PR_BODY" | grep -E "$ISSUE_REGEX" ; then
            ISSUE_NUMBER=${BASH_REMATCH[4]:-${BASH_REMATCH[6]}}
            echo "Issue #$ISSUE_NUMBER referenced in PR body"
            ISSUE_DATA=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}")
            if [[ $(echo "$ISSUE_DATA" | jq -r '.state') == "open" ]]; then
              echo "Issue #$ISSUE_NUMBER is open"
            else
              echo "Issue #$ISSUE_NUMBER is not open"
              exit 1
            fi
          else
            echo "No valid issue reference found in PR body"
            exit 1
          fi
